### ISSUE TITLE
uninitialized optionals in subschema.hpp

### ISSUE THREAD

**Issue by bpalmer7440** [tristanpenman/valijson#124] opened 2021-04-15 01:25 UTC
We have spent a good bit of time debugging a segfault in our project that uses valijson. The error happens when the destructor for the valijson::Subschema object exits. The address that malloc crashes on is typed as optional with a "contained value", but it does not have a valid address. I verified that none of the set functions are called for these variables with our schema file. We are using the PicoJson adapter. Here is a print of one of the valijson::Subschema addresses from gdb:
p *(valijson::Subschema *)(0x555555a55030)
$238 = {_vptr.Subschema = 0x555555a2ebd8 <vtable for valijson::Subschema+16>, m_allocFn = 0x7ffff755a280 <operator new(unsigned long)>, m_freeFn = 0x7ffff7558390 <operator delete(void*)>, 
  m_alwaysInvalid = false, m_constraints = std::vector of length 1, capacity 1 = {0x555555a57a70}, m_description = std::optional<std::string> = {
    [contained value] = <error: Cannot access memory at address 0x722422207b203a00>}, m_id = std::optional<std::string> = {
    [contained value] = <error: Cannot access memory at address 0xa2c7d20200a7d00>}, m_title = std::optional<std::string> = {
    [contained value] = <error: Cannot access memory at address 0x202020200a2c2200>}}

For this case, malloc crashes saying that it cannot access 0x202020200a2c2200. When I add initialization code to the constructors in subschema.hpp our crash goes away: (note that for C++11, nullopt is experimental, but for C++17 it is included in the std namespace). 

    Subschema()
      : m_allocFn(::operator new)
      , m_freeFn(::operator delete)
      , m_alwaysInvalid(false) {
        m_description = std::experimental::nullopt;
        m_id = std::experimental::nullopt;
        m_title = std::experimental::nullopt;
      }

    /**
     * @brief  Construct a new Subschema using custom memory management
     *         functions
     *
     * @param  allocFn  malloc- or new-like function to allocate memory
     *                  within Schema, such as for Subschema instances
     * @param  freeFn   free-like function to free memory allocated with
     *                  the `customAlloc` function
     */
    Subschema(CustomAlloc allocFn, CustomFree freeFn)
      : m_allocFn(allocFn)
      , m_freeFn(freeFn)
      , m_alwaysInvalid(false) {
        m_description = std::experimental::nullopt;
        m_id = std::experimental::nullopt;
        m_title = std::experimental::nullopt;
      }

**Comment by tristanpenman** [comment] 2021-04-15 01:29
Thanks for taking the time to write this up, and with such a great level of detail. I should be able to take a look at it over the weekend, and can hopefully get a fix out.

**Comment by tristanpenman** [comment] 2021-05-20 06:11
Apologies it took me so long to get to this. Although I was not able to reproduce the issue (on my Mac), I've just pushed a change (commit 3740dc5) that is similar to what you've suggested.

When C++17 is not being used, Valijson currently uses an optional implementation in compat/optional.hpp. This defines the `std::experimental::` namespace, but the library also aliases it to `opt::`. When C++17 is used, `std::` is aliased to `opt::` and regular `std::optional` will be used.

So I think initialising the optionals using `opt::nullopt` should behave the same as your workaround. I'm going to close the issue for now, but feel free to re-open it if you still experience any issues.

**Closed by tristanpenman** 2021-05-20 06:11 UTC
