### ISSUE TITLE
valijson failed to return error msg when use if-else

### ISSUE THREAD

**Issue by danielab1** [tristanpenman/valijson#131] opened 2021-07-22 12:56 UTC
hey, I used the if-else statement  in my schema, I see that the valijson failed to validate the schema but isn't print any error message, 

this is the code I run - 

    Validator validator;
    RapidJsonAdapter myTargetAdapter(doc);
    ValidationResults results;

    if (!validator.validate(mySchema, myTargetAdapter, &results)) {
        std::stringstream err_oss;
        ValidationResults::Error error;
        int error_num = 1;
        while (results.popError(error)) {
            std::string context;
            for (auto& val : error.context) {
                context += val;
            }

            err_oss << "Error #" << error_num << std::endl
                    << "  context: " << context << std::endl
                    << "  desc:    " << error.description << std::endl;
            ++error_num;
        }
        std::string error_string(err_oss.str());
        if (!error_string.empty()) {
            m_logger->error(err_oss.str());
        } else {
            m_logger->error("Error occurred while schema validating the following JSON: \n {} \n", json);
        }

        return false;
    }

thanks a lot.

**Comment by lightydo** [comment] 2021-07-26 20:09
version 0.4 seems to resolve this issue.

**Comment by tristanpenman** [comment] 2021-07-26 22:57
Glad to hear you got this working. This was probably fixed in this commit: https://github.com/tristanpenman/valijson/commit/cbcde15c0b48d2a710139296f88a5cd282ef8fbd

Sounds like the issue is resolved, so I'm going to close this ticket for now. Feel free to re-open it if you discover any related problems.

**Closed by tristanpenman** 2021-07-26 22:57 UTC
