### ISSUE TITLE
segfault with commit ee2d24714a10fc486d160a50f58aecdcfe988e88

### ISSUE THREAD

**Issue by jhjensen** [tristanpenman/valijson#17] opened 2016-02-11 15:11 UTC
on centos 6 I compiled and ran the attached program with 
`(
    set -e ; 
    . /opt/rh/devtoolset-3/enable; 
    gcc --version  ; \
     g++ -g -Og -I ../valijson/include -I /usr/local/akamai/include -I poc -std=gnu++11 -lboost_regex              
           testval.cc c-11-release/json/jsoncpp.o ; ./a.out
 );`

and got the following output:

> gcc (GCC) 4.9.2 20150212 (Red Hat 4.9.2-6)
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
testval.cc:88: doc 
{
	"bar" : "1.1.1.1",
	"foo" : -10
}
 int main(int, char**)
testval.cc:89: schema
{
	"additionalProperties" : false,
	"properties" : 
	{
		"bar" : 
		{
			"pattern" : "1.1.1.1",
			"type" : "string"
		},
		"foo" : 
		{
			"maximum" : 2147483647,
			"minimum" : 0,
			"type" : "integer"
		}
	},
	"required" : [ "foo", "bar" ],
	"type" : "object"
}
 int main(int, char**)
a.out: /usr/local/akamai/include/boost/smart_ptr/shared_ptr.hpp:641: typename boost::detail::sp_dereference<T>::type boost::shared_ptr<T>::operator*() const [with T = boost::regex_traits_wrapper<boost::regex_traits<char> >; typename boost::detail::sp_dereference<T>::type = boost::regex_traits_wrapper<boost::regex_traits<char> >&]: Assertion `px != 0' failed.
bash: line 1: 12969 Aborted                 ./a.out

gdb shows:

> Program received signal SIGABRT, Aborted.
0x00007ffff6fe88e5 in raise () from /lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install boost-regex-1.41.0-25.el6.centos.x86_64 libgcc-4.4.7-11.el6.x86_64 libicu-4.2.1-9.1.el6_2.x86_64 libstdc++-4.4.7-11.el6.x86_64
(gdb) bt
#0  0x00007ffff6fe88e5 in raise () from /lib64/libc.so.6
#1  0x00007ffff6fea0c5 in abort () from /lib64/libc.so.6
#2  0x00007ffff6fe1a0e in __assert_fail_base () from /lib64/libc.so.6
#3  0x00007ffff6fe1ad0 in __assert_fail () from /lib64/libc.so.6
#4  0x0000000000430217 in operator* (this=<optimized out>)
    at /usr/local/akamai/include/boost/smart_ptr/shared_ptr.hpp:641
#5  get_traits (this=<optimized out>)
    at /usr/local/akamai/include/boost/regex/v4/basic_regex.hpp:283
#6  get_traits (this=0x7fffffffd380)
    at /usr/local/akamai/include/boost/regex/v4/basic_regex.hpp:618
#7  perl_matcher (l_base=..., f=<optimized out>, e=..., what=..., end=..., 
    first=..., this=0x7fffffffd3d0)
    at /usr/local/akamai/include/boost/regex/v4/perl_matcher.hpp:363
#8  boost::regex_search<__gnu_cxx::__normal_iterator<char const*, std::string>, char, boost::regex_traits<char, boost::cpp_regex_traits<char> > > (first=..., 
    last=..., e=..., flags=flags@entry=boost::regex_constants::match_default)
    at /usr/local/akamai/include/boost/regex/v4/regex_search.hpp:144
#9  0x0000000000431173 in regex_search<std::char_traits<char>, std::allocator<char>, char, boost::regex_traits<char> > (
    flags=boost::regex_constants::match_default, e=..., s="1.1.1.1")
    at /usr/local/akamai/include/boost/regex/v4/regex_search.hpp:163
#10 valijson::ValidationVisitor<valijson::adapters::JsonCppAdapter>::visit (
    this=0x661858, constraint=...)
    at ../valijson/include/valijson/validation_visitor.hpp:784
#11 0x000000000040975e in valijson::constraints::BasicConstraint<valijson::constraints::PatternConstraint>::accept (this=<optimized out>, visitor=...)
    at ../valijson/include/valijson/constraints/basic_constraint.hpp:41
#12 0x0000000000409696 in valijson::ValidationVisitor<valijson::adapters::JsonCppAdapter>::validationCallback (constraint=..., visitor=...)
    at ../valijson/include/valijson/validation_visitor.hpp:1651
#13 0x00000000004096ae in operator()<bool, bool (*)(const valijson::constraints::Constraint&, valijson::ValidationVisitor<valijson::adapters::JsonCppAdapter>&), boost::_bi::list1<const valijson::constraints::Constraint&> > (
    a=<synthetic pointer>, f=<optimized out>, this=<optimized out>)
    at /usr/local/akamai/include/boost/bind/bind.hpp:303
#14 operator()<const valijson::constraints::Constraint&> (a1=..., 
    this=<optimized out>) at /usr/local/akamai/include/boost/bind/bind.hpp:905
#15 boost::detail::function::function_obj_invoker1<boost::_bi::bind_t<bool, bool (*)(valijson::constraints::Constraint const&, valijson::ValidationVisitor<valijson::adapters::JsonCppAdapter>&), boost::_bi::list2<boost::arg<1>, boost::_bi::value<valijson::ValidationVisitor<valijson::adapters::JsonCppAdapter> > > >, bool, valijson::constraints::Constraint const&>::invoke (function_obj_ptr=..., 
    a0=...)
    at /usr/local/akamai/include/boost/function/function_template.hpp:138
#16 0x00000000004150b5 in operator() (a0=..., this=0x7fffffffd590)
    at /usr/local/akamai/include/boost/function/function_template.hpp:773
#17 apply (applyFunction=..., this=0x7fffffffd810)
    at ../valijson/include/valijson/subschema.hpp:111
#18 valijson::ValidationVisitor<valijson::adapters::JsonCppAdapter>::validateSchema (this=this@entry=0x7fffffffd860, subschema=...)
    at ../valijson/include/valijson/validation_visitor.hpp:87
#19 0x000000000042e70c in valijson::ValidationVisitor<valijson::adapters::JsonCppAdapter>::ValidatePropertySubschemas::operator()<std::basic_string<char, std::char_traits<char>, valijson::internal::CustomAllocator<char> > > (
    this=this@entry=0x7fffffffda60, propertyName="bar", subschema=0x6605f0)
    at ../valijson/include/valijson/validation_visitor.hpp:1492
#20 0x000000000042e93e in valijson::constraints::PropertiesConstraint::applyToProperties<valijson::ValidationVisitor<valijson::adapters::JsonCppAdapter>::ValidatePropertySubschemas> (this=this@entry=0x661220, fn=...)
    at ../valijson/include/valijson/constraints/concrete_constraints.hpp:850
#21 0x0000000000430b11 in valijson::ValidationVisitor<valijson::adapters::JsonCppAdapter>::visit (this=0x660438, constraint=...)
    at ../valijson/include/valijson/validation_visitor.hpp:835
#22 0x0000000000409742 in valijson::constraints::BasicConstraint<valijson::constraints::PropertiesConstraint>::accept (this=<optimized out>, visitor=...)
    at ../valijson/include/valijson/constraints/basic_constraint.hpp:41
#23 0x0000000000409696 in valijson::ValidationVisitor<valijson::adapters::JsonCppAdapter>::validationCallback (constraint=..., visitor=...)
    at ../valijson/include/valijson/validation_visitor.hpp:1651
---Type <return> to continue, or q <return> to quit---
#24 0x00000000004096ae in operator()<bool, bool (*)(const valijson::constraints::Constraint&, valijson::ValidationVisitor<valijson::adapters::JsonCppAdapter>&), boost::_bi::list1<const valijson::constraints::Constraint&> > (
    a=<synthetic pointer>, f=<optimized out>, this=<optimized out>)
    at /usr/local/akamai/include/boost/bind/bind.hpp:303
#25 operator()<const valijson::constraints::Constraint&> (a1=..., 
    this=<optimized out>) at /usr/local/akamai/include/boost/bind/bind.hpp:905
#26 boost::detail::function::function_obj_invoker1<boost::_bi::bind_t<bool, bool (*)(valijson::constraints::Constraint const&, valijson::ValidationVisitor<valijson::adapters::JsonCppAdapter>&), boost::_bi::list2<boost::arg<1>, boost::_bi::value<valijson::ValidationVisitor<valijson::adapters::JsonCppAdapter> > > >, bool, valijson::constraints::Constraint const&>::invoke (function_obj_ptr=..., 
    a0=...)
    at /usr/local/akamai/include/boost/function/function_template.hpp:138
#27 0x00000000004150b5 in operator() (a0=..., this=0x7fffffffdb90)
    at /usr/local/akamai/include/boost/function/function_template.hpp:773
#28 apply (applyFunction=..., this=0x7fffffffdf80)
    at ../valijson/include/valijson/subschema.hpp:111
#29 valijson::ValidationVisitor<valijson::adapters::JsonCppAdapter>::validateSchema (this=this@entry=0x7fffffffde30, subschema=...)
    at ../valijson/include/valijson/validation_visitor.hpp:87
#30 0x0000000000415308 in valijson::Validator::validate<valijson::adapters::JsonCppAdapter> (this=this@entry=0x7fffffffdeeb, schema=..., target=..., 
    results=results@entry=0x7fffffffdf80)
    at ../valijson/include/valijson/validator.hpp:69
#31 0x0000000000409225 in main (argc=<optimized out>, argv=<optimized out>)
    at testval.cc:98
(gdb) 

This core dump doesn't happen with commit a1d330e2853f91180ca42239b666805b2a4ac43c

[test.zip](https://github.com/tristanpenman/valijson/files/126551/test.zip

**Comment by tristanpenman** [comment] 2016-02-11 15:33
Thanks for the detailed bug report. It definitely warrants further investigation, though it may be a few days before I can look into this myself.

I noticed in the output that boost-regex has been provided by the boost-regex-1.41.0-25.el6.centos.x86_64 package. I have only tested Valijson against versions of going back to boost 1.54, so it would be helpful if you could test against a later version of boost using the same CentOS and GCC releases that you've used here.

Although this issue has clearly been introduced after recent changes, reproducing the issue with a later version of boost (or not) may help to narrow down the actual cause.

**Comment by jhjensen** [comment] 2016-02-11 17:24
That gdb regex version message was caused by my not setting LD_LIBRARY_PATH when I ran in gdb.  I fixed that to point at the right boost library, and that message  went away.  The stack trace appeared to be the same.

**Comment by jhjensen** [comment] 2016-02-11 17:48
BTW, since the interface seems to be in play, I would vote for something like:

Validator(Adaptor &schema, TypeCheckingMode);

ValidationResults(const Validator&, Adaptor &jsonToBeValidated);

**Comment by tristanpenman** [comment] 2016-02-13 00:36
I have set up a quick test environment using CentOS 6.5 (installed from the minimal image), but have not been able to reproduce the issue yet. I have installed GCC 4.9.2 using the 'devtoolset-3-gcc' package:
```
yum install centos-release-scl-rh
yum install devtoolset-3-gcc devtoolset-3-gcc-c++
scl enable devtoolset-3 bash
```
using boost 1.59:
```
wget http://repo.enetres.net/enetres.repo -O /etc/yum.repos.d/enetres.repo
yum install boost-devel
```

I've used the same build command as you listed above, so I'm wondering if there is anything that I have missed, or if I should try again using different package versions.

**Comment by jhjensen** [comment] 2016-02-13 02:01
Your set up sounds pretty right.  I have a pretty out of date centos 6.4, but that doesn't seem to likely to be the problem.  I could build another vm.  I will try and investigate further when I get a chance.  

Annoyingly, I just ran my a.out, and it didn't crash.  I may have changed the source since I uploaded. will have to investigate it later.

**Comment by tristanpenman** [comment] 2016-02-17 17:01
I am going to close this issue, since the investigation into the issue seems inconclusive. However, if you have similar problems again, please feel to re-open the issue.

**Closed by tristanpenman** 2016-02-17 17:01 UTC
