### ISSUE TITLE
Improve Error handling with schema description

### ISSUE THREAD

**Issue by philippelbilberry** [tristanpenman/valijson#72] opened 2018-12-01 15:53 UTC
Hi,

first, thanks for this lib, it's great.

it would be nice to have the schema field description when an error occurs.

Like  (simplified)

schema :
{
"properties": {
   "field" : {
   "type": "string"
   "description": "this field is for ..."
   },
"required": ["field"]
}

json:
{
"field": 42 // trigger error
}

On error: Error class should contains the schema description : "this field is for ..."
class Error {
description: .... bad type... 
schema_desc: "this field is for ..."
context: [<root>,...]
}

Thks,

**Comment by tristanpenman** [comment] 2020-09-04 10:22
I spent some time looking into how this could be done. Although it is not all that difficult, it will involve touching a lot of code. I'm reluctant to make large changes, because the library is relatively stable and I don't want to introduce regressions.

I'm going to close this for now, but feel free to re-open the issue, if you feel strongly that this would be beneficial.

**Comment by tristanpenman** [comment] 2020-11-07 04:24
I'm going to re-open this issue as something that I would like to explore for the 1.0 release.

**Comment by tristanpenman** [comment] 2022-09-13 05:05
This not likely to ever happen at this stage.

**Closed by tristanpenman** 2022-09-13 05:05 UTC
