### ISSUE TITLE
Rely on C++11 instead of Boost

### ISSUE THREAD

**Issue by ansgri** [tristanpenman/valijson#15] opened 2016-01-30 11:25 UTC
I've found valijson an excellent library, but one reason that could limit its adoption within my company is the Boost dependency.

We're actually considering forking valijson for this reason if needed, the question is: would this development be welcomed by you, the maintainer, to be merged later?

As I see it, with (already not so) new c++ standard you'd get almost all you need (regexes and smart pointers were in TR1 already), the other things being quite minor (iterator_facade, boost::optional and pointer containers).
This library very gracefully abstracts away the concrete JSON library dependency, so getting rid of Boost dependency would be appropriate.

**Comment by tristanpenman** [comment] 2016-01-30 17:00
I would certainly be interested in this, although it could mean giving up C++03 support. But to be honest, supporting C++03 is as important as it was when I first started working on this library. Back then it was intended for use in a company project that never got off the ground.

I would recommend that any forks start with the code on the 'refactor-memory-management' branch. This branch tweaks the semantics around memory management for constraints and subschemas, and is going to be merged into master soon.

The changes on the 'refactor-memory-management' branch solve some circular reference issues that are blocking support for JSON References in the schema parser, and should reduce the usage of boost::shared_ptr within that code.

**Comment by ansgri** [comment] 2016-01-30 19:49
Thanks for your reply. We'll be trying out valijson for a while in projects where boost is not a problem, and I'll inform you when/if we'll be going to proceed with «de-boosting».
Could you be more specific which compiler versions are you aiming to support?

**Comment by MyLittleRobo** [comment] 2016-02-02 10:04
I believe you can keep compatibility with C++03 is some cases using macro and namespace renaming.

```c++
#ifdef VALIJSON_USE_BOOST
#include <boost/regex.hpp>
namespace cpp = boost;
#else // also need check if compiler has proper support of c++11
#include <regex>
namespace cpp = std;
#endif

// use cpp instead of boost everywhere in actual code
```

**Comment by tristanpenman** [comment] 2016-07-29 02:59
Just tidying up old issues, and I think it is best to close this issue for now.

Valijson is basically in maintenance-mode these days, so efforts to support C++11 will likely be limited to changes that will improve performance without breaking backwards compatibility.

**Closed by tristanpenman** 2016-07-29 02:59 UTC
